[workspace]
channels = ["conda-forge"]
name = "Beamline workflow"
platforms = ["linux-64"]

[dependencies]
python = "<3.13"
tiled-client = ">=0.2.3"
ipython = ">=9.10.0,<10"
opencv = "*"
scikit-image = ">=0.26.0,<0.27"
hxntools = ">=0.6.5,<0.7"
pyqt = ">=5.15.11,<6"
